#############################################################################
# Makefile for building: opencsg
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mo. Sep 15 21:55:57 2014
# Project:  opencsg.pro
# Template: subdirs
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile opencsg.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-src \
		sub-example

src//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) src.pro -o $(MAKEFILE)
sub-src-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) src/ || $(MKDIR) src/ 
	cd src/ && $(QMAKE) src.pro -o $(MAKEFILE)
sub-src: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE)
sub-src-make_default: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) 
sub-src-make_first: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) first
sub-src-all: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) all
sub-src-clean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) clean
sub-src-distclean: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) distclean
sub-src-install_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) install
sub-src-uninstall_subtargets: src//$(MAKEFILE) FORCE
	cd src/ && $(MAKE) -f $(MAKEFILE) uninstall
example//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) example/ || $(MKDIR) example/ 
	cd example/ && $(QMAKE) example.pro -o $(MAKEFILE)
sub-example-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) example/ || $(MKDIR) example/ 
	cd example/ && $(QMAKE) example.pro -o $(MAKEFILE)
sub-example: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE)
sub-example-make_default: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE) 
sub-example-make_first: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE) first
sub-example-all: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE) all
sub-example-clean: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE) clean
sub-example-distclean: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE) distclean
sub-example-install_subtargets: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE) install
sub-example-uninstall_subtargets: example//$(MAKEFILE) FORCE
	cd example/ && $(MAKE) -f $(MAKEFILE) uninstall

qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile opencsg.pro

qmake_all: sub-src-qmake_all sub-example-qmake_all FORCE

make_default: sub-src-make_default sub-example-make_default FORCE
make_first: sub-src-make_first sub-example-make_first FORCE
all: sub-src-all sub-example-all FORCE
clean: sub-src-clean sub-example-clean FORCE
distclean: sub-src-distclean sub-example-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-src-install_subtargets sub-example-install_subtargets FORCE
uninstall_subtargets: sub-src-uninstall_subtargets sub-example-uninstall_subtargets FORCE

sub-src-check: src/$(MAKEFILE)
	cd src/ && $(MAKE) -f $(MAKEFILE) check
sub-example-check: example/$(MAKEFILE)
	cd example/ && $(MAKE) -f $(MAKEFILE) check
check: sub-src-check sub-example-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

