#############################################################################
# Makefile for building: opencsg
# Generated by qmake (1.06c) (Qt 3.2.0) on: Thu Apr 22 15:53:49 2004
# Project:  opencsg.pro
# Template: subdirs
# Command: $(QMAKE) -o Makefile opencsg.pro
#############################################################################

MAKEFILE =	Makefile
DEL_FILE =    rm -f
CHK_DIR_EXISTS= test -d
MKDIR    = mkdir -p
SUBTARGETS =	 \
		sub-src \
		sub-example

first: all

all: Makefile $(SUBTARGETS)

src/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "src" || $(MKDIR) "src"
sub-src: src/$(MAKEFILE)
	cd src && $(MAKE) -f $(MAKEFILE)

example/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) "example" || $(MKDIR) "example"
sub-example: example/$(MAKEFILE) 
	cd example && $(MAKE) -f $(MAKEFILE)

all: $(SUBTARGETS)
clean uninstall uicables mocables install uiclean mocclean lexclean yaccclean:
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; ) || true
	 ( [ -d example ] && cd example ; $(MAKE) -f $(MAKEFILE) $@; ) || true
distclean:
	 ( [ -d src ] && cd src ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true
	 ( [ -d example ] && cd example ; $(MAKE) -f $(MAKEFILE) $@; $(DEL_FILE) $(MAKEFILE); ) || true

FORCE:

